#spring.session.store-type=jdbc
#spring.datasource.data-username=root
#spring.datasource.data-password=123
server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  thymeleaf:
    cache: false
#  devtools:
#    livereload:
#      enabled: true #是否支持livereload
#      port: 35729
#    restart:
#      enabled: true #是否支持热部署
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false

  datasource:
    url: jdbc:mysql://192.168.2.88:3306/jman?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
    #mysql5
    #driver-class-name: com.mysql.jdbc.Driver
    #mysql6
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id


app:
  title: 后台
  indexPage: https://github.com/jicg/jman
  icon: https://portrait.gitee.com/uploads/avatars/user/149/448289_jicg_1578924211.png!avatar100