#spring.session.store-type=jdbc
#spring.datasource.data-username=root
#spring.datasource.data-password=123
server:
  port: 8082
#  error:
#    whitelabel:
#      enabled: false

spring:
  thymeleaf:
    cache: false
  #  devtools:
  #    livereload:
  #      enabled: true #是否支持livereload
  #      port: 35729
  #    restart:
  #      enabled: true #是否支持热部署
  #  mvc:
  #    throw-exception-if-no-handler-found: true
  #  resources:
  #    add-mappings: false

  datasource:
    url: jdbc:mysql://192.168.1.88:3306/jman?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: abc123
    #mysql5
    #driver-class-name: com.mysql.jdbc.Driver
    #mysql6
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: redis
  #    store-type: jdbc
  #    jdbc:
  #      initialize-schema: always
  quartz:
    # 将任务等保存化到数据库
    job-store-type: jdbc
    # 程序结束时会等待quartz相关的内容结束
    wait-for-jobs-to-complete-on-shutdown: true
    # QuartzScheduler启动时更新己存在的Job,这样就不用每次修改targetObject后删除qrtz_job_details表对应记录
    overwrite-existing-jobs: true
    scheduler-name: jicg-text
    # 这里居然是个map，搞得智能提示都没有，佛了
    properties:
      org:
        quartz:
          # scheduler相关
          scheduler:
            # scheduler的实例名
            instanceName: scheduler
            instanceId: AUTO
          # 持久化相关
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            # 表示数据库中相关表是QRTZ_开头的
            tablePrefix: QRTZ_
            useProperties: false
          # 线程池相关
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数
            threadCount: 10
            # 线程优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    jdbc:
      initialize-schema: never
  redis:
    port: 6379
    host: 192.168.1.88
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id


app:
  title: 后台
  indexPage: https://github.com/jicg/jman
  icon: https://portrait.gitee.com/uploads/avatars/user/149/448289_jicg_1578924211.png!avatar100